version: "3"

services:
  rtmp:
    image: tiangolo/nginx-rtmp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/stat.xsl:/stat/stat.xsl
      - ./nginx/.htpasswd:/pass/.htpasswd
    ports:
      - "1935:1935"
      - "80:80"
  auth:
    image: "node:14-alpine"
    environment:
      STREAM_KEY: ${STREAM_KEY}
    working_dir: /usr/src/app
    volumes:
      - ./auth:/usr/src/app
    command: sh -c "npm i && npm start"
